#!/bin/bash

source python-2.7.4

PATH_TO_SPOUTP=$HOME/spoutp
SPOUTP_CLUSTER=$PATH_TO_SPOUTP/spoutp_cluster.py
DEFAULT_QUEUE=TSL-Test128

# python $SPOUTP_CLUSTER $1 $2 $DEFAULT_QUEUE $PATH_TO_SPOUTP
python $SPOUTP_CLUSTER --input=$1 --output=$2 --threads=$3 --queue=$DEFAULT_QUEUE --path-to-spoutp=$PATH_TO_SPOUTP --get-lsf-mails

